version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cashTracker
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgres
    container_name: api
    ports:
      - '3000:3000'


networks:
  postgres:
    driver: bridge

volumes:
  postgres:





# postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   env_file:
  #     - .env
  #   environment:
  #     # POSTGRES_USER: ${DB_USERNAME}
  #     # POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     PGDATA: /data/postgres
  #     POSTGRES_DB: cash_tracker
  #   volumes:
  #     - postgres:/data/postgres
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres
  #   restart: unless-stopped
